#!/bin/bash
# 脚本功能：配置公司yum源（配置网关，CentOS-Base.repo, hosts, DNS, ali source, yum cache update）
# 前置条件：管理网已配置
# 使用方法：在任何位置执行该脚本



# get nic IP
read -p "[INFO] Please enter your management nework IP:" nic_ip
# check IP format
if [[ $nic_ip =~ ^([0-9]{1,3}.){3}[0-9]{1,3}$ ]]; then
    echo "[INFO] Starting"
else
    echo "[ERROR]Please enter correct IP"
    exit 0
fi
# get the name of nic
nic=`ifconfig | sed -n "/$nic_ip/{x;p};h"| awk -F : '{print $1}'`
echo "The NIC of the IP is $nic"

#nic config file path
nic_file=/etc/sysconfig/network-scripts/ifcfg-$nic

# get gateway ip
read -p "[INFO]Please enter your gateway IP:" gateway
# check ip format
if [[ $gateway =~ ^([0-9]{1,3}.){3}[0-9]{1,3}$ ]]; then
    echo "starting"
else
    echo "[ERROR]Please enter correct IP"
    exit 0
fi
# add gateway in nic config file
if [[ `grep GATEWAY $nic_file` == "" ]]; then
    sed -i "\$aGATEWAY=$gateway" $nic_file
else
    echo "[INFO]Gateway is already configure."
fi



# revise CentOS-Base.repo -- campany source
cat > /etc/yum.repos.d/CentOS-Base.repo <<- EOF
#CentOS-Base.repo
# The mirror system uses the connecting IP address of the client and the
# update status of each mirror to pick mirrors that are updated to and
# geographically close to the client.  You should use this for CentOS updates
# unless you are manually picking other mirrors.
#
# If the mirrorlist= does not work for you, as a fall back you can try the
# remarked out baseurl= line instead.
#
#
[base]
name=CentOS-mycompany - Base
baseurl=http://rdmirrors.h3c.com/centos/\$releasever/os/\$basearch
gpgcheck=1
enabled=1
gpgkey=http://rdmirrors.h3c.com/centos/RPM-GPG-KEY-CentOS-\$releasever

[updates]
name=CentOS-mycompany - Updates
baseurl=http://rdmirrors.h3c.com/centos/\$releasever/updates/\$basearch
gpgcheck=1
enabled=1
gpgkey=http://rdmirrors.h3c.com/centos/RPM-GPG-KEY-CentOS-\$releasever

[extras]
name=CentOS-mycompany - Extras
baseurl=http://rdmirrors.h3c.com/centos/\$releasever/extras/\$basearch
gpgcheck=1
enabled=1
gpgkey=http://rdmirrors.h3c.com/centos/RPM-GPG-KEY-CentOS-\$releasever

[centosplus]
name=CentOS-mycompany - Plus
baseurl=http://rdmirrors.h3c.com/centos/\$releasever/centosplus/\$basearch
gpgcheck=1
enabled=1
gpgkey=http://rdmirrors.h3c.com/centos/RPM-GPG-KEY-CentOS-\$releasever
EOF

# revise host file
sed -i '$a10.153.3.130 rdmirrors.h3c.com' /etc/hosts

echo "[INFO]config DNS."
# config DNS
if [[ `grep nameserver /etc/resolv.conf` == "" ]]; then
    echo "nameserver 10.72.66.36" >> /etc/resolv.conf
else
    echo "DNS had been set."
fi

echo "[INFO]set ali source."
# set ali source
cat > /etc/yum.repos.d/epel.repo <<- EOF
[epel]
name=Extra Packages for Enterprise Linux 7 - \$basearch
baseurl=http://mirrors.aliyun.com/epel/7/\$basearch
failovermethod=priority
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

[epel-debuginfo]
name=Extra Packages for Enterprise Linux 7 - \$basearch - Debug
baseurl=http://mirrors.aliyun.com/epel/7/\$basearch/debug
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=0

[epel-source]
name=Extra Packages for Enterprise Linux 7 - \$basearch - Source
baseurl=http://mirrors.aliyun.com/epel/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=0
EOF

echo "[INFO]yum cache update."
# yum cache updae
yum clean all
yum makecache


# restart the nework
echo "success"
echo "[INFO]Please restart network"

